In [ ]:
import sys#THIS IS FOR GOOGLE COLAB USERS ONLY
from google.colab import files
sys.path.insert(0,'/content/drive/MyDrive/Product-Title-Classification')

In [ ]:
import sys                                                                  #THIS IS FOR GOOGLE COLAB USERS ONLY
from google.colab import files
sys.path.insert(0,'/content/drive/MyDrive/Product-Title-Classification')
!cp /content/drive/MyDrive/Product-Title-Classification/Utilities.py /content           #THIS IS FOR GOOGLE COLAB USERS ONLY
!cp /content/drive/MyDrive/Product-Title-Classification/KNNImpute.py /content

cp: cannot stat '/content/drive/MyDrive/Product-Title-Classification/Utilities.py': No such file or directory
cp: cannot stat '/content/drive/MyDrive/Product-Title-Classification/KNNImpute.py': No such file or directory


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing Local Files

In [ ]:
import KNNImpute
import Utilities

In [ ]:
# pip install sklearn

     |████████████████████████████████| 31.0 MB 124 kB/s eta 0:00:01     |████████████████████            | 19.3 MB 174 kB/s eta 0:01:07     |███████████████████████████████▋| 30.7 MB 731 kB/s eta 0:00:01
     |████████████████████████████████| 41.6 MB 49 kB/s  eta 0:00:01     |████████████████████████▉       | 32.3 MB 10 kB/s eta 0:14:19
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=3d38ad744d36d150a99d67071fefc46974d96824fce525bd128de29f5a011f02
  Stored in directory: /home/mustafa/.cache/pip/wheels/22/0b/40/fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


Importing Local Files

In [ ]:
# from KNNImpute import *
# from Utilities import *

## Importing Packages

In [ ]:
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


## Splitting Data Into Training Data and Testing Data

In [ ]:
labels=["country", "sku_id", "title", "category_lvl1","category_lvl2","category_lvl3", "description", "price", "type"]

def getTrainingDataset():
    return pd.read_csv('/content/drive/MyDrive/Product-Title-Classification/data_train.csv', header=None, names=labels)  


raw_data = getTrainingDataset()
train_df,Y1,Y2,Y3= Utilities.Cleaning_Data_Utility(raw_data) #Utilities. hatadena yahan se 
print(train_df.head())

0        Adana Gallery Suri Square Hijab – Light Pink <...
1        Cuba Heartbreaker Eau De Parfum Spray 100ml/3....
2        Andoer 150cm Cellphone Smartphone Mini Dual-He...
3        ANMYNA Complaint Silky Set 柔顺洗发配套 (Shampoo 520...
4        Argital Argiltubo Green Clay For Face and Body...
                               ...                        
36278    SADES K10 LED Backlit Wired USB Mechanical Gam...
36279    SONA 20L Electric Oven SEO 2220 <ul> <li>&nbsp...
36280    OP1001 Portable Wireless Bluetooth 2.1 Speaker...
36281    Woot-Woot TicTacToe Pillow Case (White) <ul> <...
36282    New Smart Wristband D21 Smart Bracelet Heart R...
Name: titleDescp, Length: 36283, dtype: object
                           category_lvl1 category_lvl2  \
0                                Fashion         Women   
1                        Health & Beauty   Bath & Body   
2  TV, Audio / Video, Gaming & Wearables         Audio   
3                        Health & Beauty     Hair Care   
4             

# Imputing Null Values

In [ ]:
def NullStatistics(df):
    missing_val = df.isnull().sum()
    print(missing_val)
    total_cells = np.product(df.shape)
    missing_percent = (missing_val.sum()/total_cells) *100
    print(f'\nThe missing data percent is: {missing_percent}')

NullStatistics(train_df)

unique_label_c1, unique_label_c2, unique_label_c3 = KNNImpute.preserve_label(train_df) #It has all unique values lying in ctg1 , 2 , 3 column
KNNImpute.encode(['category_lvl1', 'category_lvl2', 'category_lvl3'],train_df)        #Performed encoding for CTGLVL3 KNN
train_df_imputed = KNNImpute.impute(train_df)
train_df_imputed =  KNNImpute.clean_csv(train_df_imputed,train_df)
NullStatistics(train_df_imputed)

category_lvl1       0
category_lvl2       0
category_lvl3    2135
titleDescp          0
dtype: int64

The missing data percent is: 1.4710746079431138


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


category_lvl1    0
category_lvl2    0
category_lvl3    0
Title_desc       0
dtype: int64

The missing data percent is: 0.0


In [ ]:
temp = train_df_imputed 

In [ ]:
train_df_imputed = temp
train_df_imputed.shape

(36283, 4)

## Directly Reading From File

In [ ]:
# train_df_imputed = temp
# train_df_imputed.to_csv("clean_training_data.csv" , index=False)

In [ ]:
# train_df_imputed = pd.read_csv("clean_training_data.csv" , )
# train_df_imputed.head() 

category_lvl1  category_lvl2  category_lvl3  \
0            2.0           56.0          113.0   
1            3.0            3.0           67.0   
2            7.0            1.0           95.0   
3            3.0           23.0          147.0   
4            3.0           36.0           23.0   

                                          Title_desc  
0  adana galleri suri squar hijab light pink ul l...  
1  cuba heartbreak eau de parfum spray ml oz form...  
2  andoer cm cellphon smartphon mini dual head om...  
3  anmyna complaint silki set shampoo ml conditio...  
4  argit argiltubo green clay face bodi ml ul li ...

Splitting Data Into Training And Testing

In [ ]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X)
# X_test_features = feature_extraction.transform(X_test.values.astype('U'))

In [ ]:
X_train, X_test , Y_train , Y_test = train_test_split(X_train_features, Y1, test_size = 0.3, random_state=3 , stratify = Y1)

In [ ]:
Y_train.shape

(25398,)

Feature Extraction

In [ ]:
print(X_train_features)

  (0, 8844)	0.20669140444780615
  (0, 6509)	0.21996803699368137
  (0, 6529)	0.16898535529139208
  (0, 13520)	0.26353252165855096
  (0, 25017)	0.09569136097916549
  (0, 4920)	0.20363684473882185
  (0, 24625)	0.2749088614258273
  (0, 24580)	0.24936730479422012
  (0, 19075)	0.1519301323425332
  (0, 16849)	0.0780089820671493
  (0, 15731)	0.216601402357855
  (0, 28788)	0.07225424844998868
  (0, 20958)	0.1476446166731313
  (0, 15796)	0.12476995284687205
  (0, 12651)	0.28221774410096967
  (0, 25966)	0.1998311858009805
  (0, 26856)	0.37659487115461027
  (0, 11010)	0.31718340705761777
  (0, 273)	0.37659487115461027
  (1, 22811)	0.2136905935874917
  (1, 25350)	0.14743774062287782
  (1, 25476)	0.1139992217155386
  (1, 23090)	0.20897084135647298
  (1, 12102)	0.26457738829416816
  (1, 88)	0.30830261194693526
  :	:
  (36282, 17976)	0.28162069027997677
  (36282, 7514)	0.16688247220831284
  (36282, 19514)	0.19044165965420964
  (36282, 3528)	0.14815299634208604
  (36282, 27849)	0.05441399525371072
  (3

Applying Random Forest Classifier

In [ ]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_cat_1 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_1.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=159)

In [ ]:
# #Predicting On Training Data

# prediction_on_training_data = model_cat_1.predict(X_train_features)
# accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
# print(accuracy_on_training_data)

0.9990944168832192


In [ ]:
#Predicting On Testing Data
from sklearn.metrics import accuracy_score

prediction_on_testing_data = model_cat_1.predict(X_test)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.9028938906752412


In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

Accuracy score with Random Forest Classifier is : 
90.20670647680295
[[ 505    8    5    1   35    1   27    2    2]
 [   4  744    1    2   25    1   57   43    1]
 [   0    2 1628   13   52    0   10    1   13]
 [   0    1   37 1049  109    4    5    4    3]
 [   6    8   50   36 1654    7   31    7   15]
 [   0    1    2   12  114  340    6    0    0]
 [   9    6    5    3   17    1 2112   28    2]
 [   8   19    1    4   54    1   61  586   19]
 [   2    0   21    3   27    0    7    4 1201]]


In [ ]:
# Printing Classification Report

from sklearn.metrics import classification_report
print(classification_report(Y_test, prediction_on_testing_data))

              precision    recall  f1-score   support

         0.0       0.95      0.86      0.90       586
         1.0       0.94      0.85      0.89       878
         2.0       0.93      0.95      0.94      1719
         3.0       0.93      0.87      0.90      1212
         4.0       0.79      0.91      0.85      1814
         5.0       0.96      0.72      0.82       475
         6.0       0.91      0.97      0.94      2183
         7.0       0.88      0.77      0.82       753
         8.0       0.96      0.95      0.96      1265

    accuracy                           0.90     10885
   macro avg       0.92      0.87      0.89     10885
weighted avg       0.91      0.90      0.90     10885



## CATEGORY LEVEL 2

In [ ]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']
X_train, X_test , Y_train , Y_test = train_test_split(X, Y2, test_size = 0.3, random_state=3 , stratify = Y2)

Feature Extraction

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))
print(X_test_features)

  (0, 23719)	0.1121815911455606
  (0, 21916)	0.165843922602542
  (0, 21080)	0.16314642624619388
  (0, 20795)	0.14266694982120026
  (0, 20768)	0.4540205756824182
  (0, 20641)	0.09753398231263447
  (0, 20352)	0.1719445991665768
  (0, 18875)	0.1940325100893119
  (0, 16817)	0.1331402248498774
  (0, 14214)	0.129445894319038
  (0, 13960)	0.0795637343615029
  (0, 13565)	0.17375177314638093
  (0, 13346)	0.27287705896965436
  (0, 12974)	0.1307712728515241
  (0, 8390)	0.12818724209190857
  (0, 8056)	0.10080934942966051
  (0, 6514)	0.16600916707170177
  (0, 5064)	0.14187488607322638
  (0, 4590)	0.0935538231595422
  (0, 4565)	0.18181095630667324
  (0, 3684)	0.14047609735665126
  (0, 3181)	0.1484313169258753
  (0, 2806)	0.5248971787175488
  (0, 2487)	0.1847747462569313
  (1, 25329)	0.11951897199288575
  :	:
  (10884, 23793)	0.05005704486302929
  (10884, 23318)	0.18694686009179287
  (10884, 20641)	0.06634897697753309
  (10884, 20594)	0.12275958424836705
  (10884, 18086)	0.1468251272822115
  (10884, 

In [ ]:
X_train_features.shape

(25398, 26119)

In [ ]:
X_test_features.shape

(10885, 26119)

In [ ]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_cat_2 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_2.fit(X_train_features, Y_train)

RandomForestClassifier(n_estimators=159)

In [ ]:
#Predicting On Training Data

from sklearn.metrics import accuracy_score    

prediction_on_training_data = model_cat_2.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
print(accuracy_on_training_data)

0.9992125364201906


In [ ]:
#Predicting On Testing Data

prediction_on_testing_data = model.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.8215893431327514


In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

# CATEGORY LEVEL 3

In [ ]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']
X_train, X_test , Y_train , Y_test = train_test_split(X, Y3, test_size = 0.3, random_state=3 , stratify = Y2)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))

In [ ]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_cat_3 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_3.fit(X_train_features, Y_train)

RandomForestClassifier(n_estimators=159)

In [ ]:
#Predicting On Training Data

from sklearn.metrics import accuracy_score    

prediction_on_training_data = model_cat_3.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
print(accuracy_on_training_data)

0.9990156705252382


In [ ]:
#Predicting On Testing Data

prediction_on_testing_data = model_cat_3.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.733210840606339


In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

Accuracy score with Random Forest Classifier is : 
73.32108406063391
[[  5   0   0 ...   0   0   0]
 [  0 106   0 ...   0   0   1]
 [  0   0  13 ...   0   0   0]
 ...
 [  0   0   0 ...  16   1   0]
 [  0   0   0 ...   0   7   0]
 [  0   0   0 ...   0   0  19]]


# TESTING DATA CLEANING

In [ ]:
labels=["country", "sku_id", "title", "category_lvl1","category_lvl2","category_lvl3", "description", "price", "type"]

def getTestingDataset():
    return pd.read_csv('/content/drive/MyDrive/Product-Title-Classification/data_valid.csv', header=None, names=labels)  

raw_test_data = getTestingDataset()
test_df,Y1,Y2,Y3= Utilities.Cleaning_Data_Utility(raw_test_data) #Utilities. hatadena yahan se 
print(test_df.head())

0        Apple MacBook Pro MGXC2ZP/A 16GB i7 15.4-inch ...
1        BRAND'S® American Ginseng Triple Pack (3x 6's)...
2        Canon EOS M10 Mirrorless Digital Camera 18MP w...
3        Dell LED Monitor 23" (E2316H) <div class="prod...
4        Esprit Tallac Brave Nubuck Sand ES107601001 Be...
                               ...                        
11833    Olen Swarovski Crystal ElementsLove Birds Aust...
11834    Adele Bethany BLACK Small ladies Shoulder bag ...
11835    Spigen Neo Hybrid Series Case for iPhone 7 Plu...
11836    Anti-wrinkle Backdrop for Photo Studio Photogr...
11837    Waterproof 170° Rear View Parking Car Camera w...
Name: titleDescp, Length: 11838, dtype: object
                  category_lvl1         category_lvl2 category_lvl3  \
0           Computers & Laptops               Laptops      Macbooks   
1               Health & Beauty      Food Supplements    Well Being   
2                       Cameras            Mirrorless           NaN   
3           Computer

In [ ]:
def NullStatistics(df):
    missing_val = df.isnull().sum()
    print(missing_val)
    total_cells = np.product(df.shape)
    missing_percent = (missing_val.sum()/total_cells) *100
    print(f'\nThe missing data percent is: {missing_percent}')

NullStatistics(test_df)

unique_label_c1, unique_label_c2, unique_label_c3 = KNNImpute.preserve_label(test_df) #It has all unique values lying in ctg1 , 2 , 3 column
KNNImpute.encode(['category_lvl1', 'category_lvl2', 'category_lvl3'],test_df)        #Performed encoding for CTGLVL3 KNN
test_df_imputed = KNNImpute.impute(test_df)
test_df_imputed =  KNNImpute.clean_csv(test_df_imputed,test_df)
NullStatistics(test_df_imputed)

category_lvl1      0
category_lvl2      0
category_lvl3    687
titleDescp         0
dtype: int64

The missing data percent is: 1.4508362899138367


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


category_lvl1    0
category_lvl2    0
category_lvl3    0
Title_desc       0
dtype: int64

The missing data percent is: 0.0


# CATEGORY LEVEL 1

In [ ]:
test_df.head()

category_lvl1 category_lvl2 category_lvl3  \
0             1            29            98   
1             3            15           177   
2             0            37           NaN   
3             1             8           112   
4             8            54           106   

                                          titleDescp  
0  appl macbook pro mgxc zp gb inch retina displa...  
1  brand american ginseng tripl pack x bottl x gm...  
2  canon eo mirrorless digit camera mp mm len whi...  
3  dell led monitor e h div class prod content di...  
4  esprit tallac brave nubuck sand es beig leathe...

In [ ]:
X = test_df['titleDescp']
Y1 = test_df['category_lvl1']
Y2 = test_df['category_lvl2']
Y3 = test_df['category_lvl3']

In [ ]:
X_test_tfidf = feature_extraction.transform(X)

In [ ]:
#Predicting On Testing Data

prediction_on_testing_data = model_cat_1.predict(X_test_tfidf)


In [ ]:
abc = prediction_on_testing_data.astype(int)

In [ ]:
abc

array([1, 3, 0, ..., 6, 4, 0])

In [ ]:
Y1.head()

0    1
1    3
2    0
3    1
4    8
Name: category_lvl1, dtype: object

In [ ]:
accuracy_on_testing_data = accuracy_score(Y1 , abc)
print(accuracy_on_testing_data)

ValueError: ignored