In [3]:
# import sys#THIS IS FOR GOOGLE COLAB USERS ONLY
# from google.colab import files
# sys.path.insert(0,'/content/drive/MyDrive/Product-Title-Classification')

In [5]:
# import sys                                                                  #THIS IS FOR GOOGLE COLAB USERS ONLY
# from google.colab import files
# sys.path.insert(0,'/content/drive/MyDrive/Product-Title-Classification')
# !cp /content/drive/MyDrive/Product-Title-Classification/Utilities.py /content           #THIS IS FOR GOOGLE COLAB USERS ONLY
# !cp /content/drive/MyDrive/Product-Title-Classification/KNNImpute.py /content

In [6]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importing Local Files

In [7]:
# import KNNImpute
# import Utilities

In [6]:
pip install sklearn

     |████████████████████████████████| 31.0 MB 124 kB/s eta 0:00:01     |████████████████████            | 19.3 MB 174 kB/s eta 0:01:07     |███████████████████████████████▋| 30.7 MB 731 kB/s eta 0:00:01
     |████████████████████████████████| 41.6 MB 49 kB/s  eta 0:00:01     |████████████████████████▉       | 32.3 MB 10 kB/s eta 0:14:19
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=3d38ad744d36d150a99d67071fefc46974d96824fce525bd128de29f5a011f02
  Stored in directory: /home/mustafa/.cache/pip/wheels/22/0b/40/fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


Importing Local Files

In [1]:
from KNNImpute import *
from Utilities import *

## Importing Packages

In [2]:
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/mustafa/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Splitting Data Into Training Data and Testing Data

In [20]:
# labels=["country", "sku_id", "title", "category_lvl1","category_lvl2","category_lvl3", "description", "price", "type"]

# def getTrainingDataset():
#     return pd.read_csv('data_train.csv', header=None, names=labels)  


# raw_data = getTrainingDataset()
# train_df,Y1,Y2,Y3= Cleaning_Data_Utility(raw_data) #Utilities. hatadena yahan se 
# print(train_df.head())

0        Adana Gallery Suri Square Hijab – Light Pink <...
1        Cuba Heartbreaker Eau De Parfum Spray 100ml/3....
2        Andoer 150cm Cellphone Smartphone Mini Dual-He...
3        ANMYNA Complaint Silky Set 柔顺洗发配套 (Shampoo 520...
4        Argital Argiltubo Green Clay For Face and Body...
                               ...                        
36278    SADES K10 LED Backlit Wired USB Mechanical Gam...
36279    SONA 20L Electric Oven SEO 2220 <ul> <li>&nbsp...
36280    OP1001 Portable Wireless Bluetooth 2.1 Speaker...
36281    Woot-Woot TicTacToe Pillow Case (White) <ul> <...
36282    New Smart Wristband D21 Smart Bracelet Heart R...
Name: titleDescp, Length: 36283, dtype: object
                           category_lvl1 category_lvl2  \
0                                Fashion         Women   
1                        Health & Beauty   Bath & Body   
2  TV, Audio / Video, Gaming & Wearables         Audio   
3                        Health & Beauty     Hair Care   
4             

# Imputing Null Values

In [21]:
# def NullStatistics(df):
#     missing_val = df.isnull().sum()
#     print(missing_val)
#     total_cells = np.product(df.shape)
#     missing_percent = (missing_val.sum()/total_cells) *100
#     print(f'\nThe missing data percent is: {missing_percent}')

# NullStatistics(train_df)

# unique_label_c1, unique_label_c2, unique_label_c3 = preserve_label(train_df) #It has all unique values lying in ctg1 , 2 , 3 column
# encode(['category_lvl1', 'category_lvl2', 'category_lvl3'],train_df)        #Performed encoding for CTGLVL3 KNN
# train_df_imputed = impute(train_df)
# train_df_imputed =  clean_csv(train_df_imputed,train_df)
# NullStatistics(train_df_imputed)

category_lvl1       0
category_lvl2       0
category_lvl3    2135
titleDescp          0
dtype: int64

The missing data percent is: 1.4710746079431138


/home/mustafa/.local/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


category_lvl1    0
category_lvl2    0
category_lvl3    0
Title_desc       0
dtype: int64

The missing data percent is: 0.0


In [22]:
temp = train_df_imputed 

## Directly Reading From File

In [26]:
train_df_imputed = temp
train_df_imputed.to_csv("clean_training_data.csv" , index=False)

In [3]:
train_df_imputed = pd.read_csv("clean_training_data.csv" , )
train_df_imputed.head() 

category_lvl1  category_lvl2  category_lvl3  \
0            2.0           56.0          113.0   
1            3.0            3.0           67.0   
2            7.0            1.0           95.0   
3            3.0           23.0          147.0   
4            3.0           36.0           23.0   

                                          Title_desc  
0  adana galleri suri squar hijab light pink ul l...  
1  cuba heartbreak eau de parfum spray ml oz form...  
2  andoer cm cellphon smartphon mini dual head om...  
3  anmyna complaint silki set shampoo ml conditio...  
4  argit argiltubo green clay face bodi ml ul li ...

Splitting Data Into Training And Testing

In [4]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']
X_train, X_test , Y_train , Y_test = train_test_split(X, Y1, test_size = 0.3, random_state=3 , stratify = Y1)

In [5]:
Y_train.shape

(25398,)

Feature Extraction

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))

In [7]:
print(X_train_features)

  (0, 16981)	0.062143522561221916
  (0, 14825)	0.06190906261845123
  (0, 20846)	0.10084698010861086
  (0, 5964)	0.07674462784092914
  (0, 7146)	0.10037996161500964
  (0, 13896)	0.11750587658197595
  (0, 4902)	0.07102430542943922
  (0, 19123)	0.0953740004541301
  (0, 23523)	0.13021981306142558
  (0, 3363)	0.07006688061804335
  (0, 18186)	0.0687015109331191
  (0, 24295)	0.056675062787309036
  (0, 13151)	0.08949346886584825
  (0, 5828)	0.12354929384162018
  (0, 7347)	0.09719456795824254
  (0, 15679)	0.049508410152838835
  (0, 2840)	0.05190585061900028
  (0, 18817)	0.09075895909681381
  (0, 13916)	0.09682612994152978
  (0, 3481)	0.07612744439066685
  (0, 23906)	0.16039581233877792
  (0, 2812)	0.6772696503457704
  (0, 14893)	0.07912429466908961
  (0, 1987)	0.14079388300515713
  (0, 513)	0.38332973942736503
  :	:
  (25397, 7967)	0.08652623916287899
  (25397, 7011)	0.0640816697773495
  (25397, 750)	0.044484526165596096
  (25397, 11477)	0.18598660552966553
  (25397, 14424)	0.05581947916479948


Applying Random Forest Classifier

In [8]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [9]:
from sklearn.ensemble import RandomForestClassifier
model_cat_1 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_1.fit(X_train_features, Y_train)

RandomForestClassifier(n_estimators=159)

In [10]:
#Predicting On Training Data

prediction_on_training_data = model_cat_1.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
print(accuracy_on_training_data)

0.9990944168832192


In [11]:
#Predicting On Testing Data

prediction_on_testing_data = model_cat_1.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.9029857602204869


In [49]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

Accuracy score with Random Forest Classifier is : 
90.32613688562242
[[ 503   11    5    2   34    1   29    1    0]
 [   5  747    1    2   25    2   54   41    1]
 [   0    1 1628   12   52    0   11    1   14]
 [   0    0   34 1053  107    4    5    5    4]
 [   6    8   49   41 1658    6   25    8   13]
 [   0    0    2   11  114  342    6    0    0]
 [   6    8    3    3   21    1 2118   21    2]
 [   7   21    2    6   58    2   60  580   17]
 [   2    0   18    3   28    0    7    4 1203]]


In [50]:
# Printing Classification Report

from sklearn.metrics import classification_report
print(classification_report(Y_test, prediction_on_testing_data))

              precision    recall  f1-score   support

         0.0       0.95      0.86      0.90       586
         1.0       0.94      0.85      0.89       878
         2.0       0.93      0.95      0.94      1719
         3.0       0.93      0.87      0.90      1212
         4.0       0.79      0.91      0.85      1814
         5.0       0.96      0.72      0.82       475
         6.0       0.91      0.97      0.94      2183
         7.0       0.88      0.77      0.82       753
         8.0       0.96      0.95      0.96      1265

    accuracy                           0.90     10885
   macro avg       0.92      0.87      0.89     10885
weighted avg       0.91      0.90      0.90     10885



## CATEGORY LEVEL 2

In [59]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']
X_train, X_test , Y_train , Y_test = train_test_split(X, Y2, test_size = 0.3, random_state=3 , stratify = Y2)

Feature Extraction

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))
print(X_test_features)

  (0, 23719)	0.1121815911455606
  (0, 21916)	0.165843922602542
  (0, 21080)	0.16314642624619388
  (0, 20795)	0.14266694982120026
  (0, 20768)	0.4540205756824182
  (0, 20641)	0.09753398231263447
  (0, 20352)	0.1719445991665768
  (0, 18875)	0.1940325100893119
  (0, 16817)	0.1331402248498774
  (0, 14214)	0.129445894319038
  (0, 13960)	0.0795637343615029
  (0, 13565)	0.17375177314638093
  (0, 13346)	0.27287705896965436
  (0, 12974)	0.1307712728515241
  (0, 8390)	0.12818724209190857
  (0, 8056)	0.10080934942966051
  (0, 6514)	0.16600916707170177
  (0, 5064)	0.14187488607322638
  (0, 4590)	0.0935538231595422
  (0, 4565)	0.18181095630667324
  (0, 3684)	0.14047609735665126
  (0, 3181)	0.1484313169258753
  (0, 2806)	0.5248971787175488
  (0, 2487)	0.1847747462569313
  (1, 25329)	0.11951897199288575
  :	:
  (10884, 23793)	0.05005704486302929
  (10884, 23318)	0.18694686009179287
  (10884, 20641)	0.06634897697753309
  (10884, 20594)	0.12275958424836705
  (10884, 18086)	0.1468251272822115
  (10884, 

In [62]:
X_train_features.shape

(25398, 26119)

In [63]:
X_test_features.shape

(10885, 26119)

In [64]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [66]:
from sklearn.ensemble import RandomForestClassifier
model_cat_2 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_2.fit(X_train_features, Y_train)

RandomForestClassifier(n_estimators=159)

In [67]:
#Predicting On Training Data

from sklearn.metrics import accuracy_score    

prediction_on_training_data = model_cat_2.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
print(accuracy_on_training_data)

0.9992125364201906


In [68]:
#Predicting On Testing Data

prediction_on_testing_data = model.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.8215893431327514


In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

# CATEGORY LEVEL 3

In [8]:
X = train_df_imputed['Title_desc']
Y1 = train_df_imputed['category_lvl1']
Y2 = train_df_imputed['category_lvl2']
Y3 = train_df_imputed['category_lvl3']
X_train, X_test , Y_train , Y_test = train_test_split(X, Y3, test_size = 0.3, random_state=3 , stratify = Y2)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_train_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))

In [10]:
import math
X_train.shape
number_of_trees = X_train.shape
estimated_trees = math.sqrt(number_of_trees[0])
estimated_trees = int(math.floor(estimated_trees))
print(estimated_trees)

159


In [11]:
from sklearn.ensemble import RandomForestClassifier
model_cat_3 = RandomForestClassifier(n_estimators = estimated_trees) 
model_cat_3.fit(X_train_features, Y_train)

RandomForestClassifier(n_estimators=159)

In [12]:
#Predicting On Training Data

from sklearn.metrics import accuracy_score    

prediction_on_training_data = model_cat_3.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)
print(accuracy_on_training_data)

0.9990156705252382


In [14]:
#Predicting On Testing Data

prediction_on_testing_data = model_cat_3.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)
print(accuracy_on_testing_data)

0.733210840606339


In [15]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

print('Accuracy score with Random Forest Classifier is : ')
print(metrics.accuracy_score(Y_test, prediction_on_testing_data)*100)
mat = confusion_matrix(Y_test, prediction_on_testing_data)
print(mat)

Accuracy score with Random Forest Classifier is : 
73.32108406063391
[[  5   0   0 ...   0   0   0]
 [  0 106   0 ...   0   0   1]
 [  0   0  13 ...   0   0   0]
 ...
 [  0   0   0 ...  16   1   0]
 [  0   0   0 ...   0   7   0]
 [  0   0   0 ...   0   0  19]]


# TESTING DATA CLEANING

In [24]:
title = ['category_lvl1' , 'category_lvl2' , 'category_lvl3' , 'Title_desc']
test_df_imputed = pd.read_csv("clean_testing_data.csv" , names=title)
# test_df_imputed.head() 
temp_test_df = test_df_imputed[0:11388]

# CATEGORY LEVEL 1

In [58]:
labels=["country", "sku_id", "title", "category_lvl1","category_lvl2","category_lvl3", "description", "price", "type"]
df = pd.read_csv('data_valid.csv' , header=None, names=labels)
print(df['category_lvl1'].nunique()) # 9 distinct classes in category 1
print(df['category_lvl2'].nunique()) # 57 distinct classes in category 1
print(df['category_lvl3'].nunique())

print(df['category_lvl1'].mode())
print(df['category_lvl2'].mode())
print(df['category_lvl3'].mode())

9
57
184
0    Mobiles & Tablets
Name: category_lvl1, dtype: object
0    Accessories
Name: category_lvl2, dtype: object
0    Phone Cases
Name: category_lvl3, dtype: object


In [25]:
X = temp_test_df['Title_desc']
Y1 = temp_test_df['category_lvl1']
Y2 = temp_test_df['category_lvl2']
Y3 = temp_test_df['category_lvl3']

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

feature_extraction = TfidfVectorizer(min_df = 1, stop_words = 'english' , lowercase = 'True')

X_features = feature_extraction.fit_transform(X_train.values.astype('U'))
X_test_features = feature_extraction.transform(X_test.values.astype('U'))

In [27]:
#Predicting On Testing Data

prediction_on_testing_data = model_cat_1.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y1, prediction_on_testing_data)
print(accuracy_on_testing_data)

ValueError: Found input variables with inconsistent numbers of samples: [11388, 10885]